Homework 43 completed
Borisko130/hibernate-homework pull request #8
Opened 2020-10-15 15:17 UTC by Borisko130

2020-10-15 17:30 UTC, MaliukDaria commented on .gitignore
> +logs/*
add an empty line at the end of the file

2020-10-15 17:30 UTC, MaliukDaria commented on src/main/java/com/dev/cinema/Main.java
> +    private static final Logger logger = Logger.getLogger(CinemaHallDaoImpl.class);
why CinemaHallDaoImpl.class?

2020-10-15 17:30 UTC, MaliukDaria commented on src/main/java/com/dev/cinema/security/impl/AuthenticationServiceImpl.java
> +        logger.info("User with email " + email + " logs in");
what if there is no such user in DB?

2020-10-15 17:30 UTC, MaliukDaria commented on src/main/java/com/dev/cinema/security/impl/AuthenticationServiceImpl.java
> +        logger.info("Registering new User");
maybe you should add some information about registering user? (e-mail for example)

2020-10-15 20:18 UTC, KseniiaMakarova requested changes

2020-10-15 20:18 UTC, KseniiaMakarova commented on .gitignore
> +logs/*
I agree

2020-10-15 20:18 UTC, KseniiaMakarova commented on src/main/resources/log4j.properties
> +log4j.appender.CONSOLE.threshold=DEBUG
let's add log4j.appender.stdout.Target

2020-10-15 20:18 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/security/impl/AuthenticationServiceImpl.java
> +        logger.info("User with email " + email + " logs in");
```suggestion
        logger.info("User with email " + email + " tries to log in");
```

2020-10-15 20:18 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/Main.java
> +    private static final Logger logger = Logger.getLogger(CinemaHallDaoImpl.class);
```suggestion
    private static final Logger logger = Logger.getLogger(Main.class);
```

2020-10-15 20:18 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/Main.java
>          shoppingCartService.addSession(movieSession, user);
where are movies, moviesessions, users and other entities saved to DB before we can proceed?

2020-10-15 20:18 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/Main.java
> +        logger.debug(orderService.completeOrder(shoppingCart.getTickets(),
let's use `info` level here everywhere

2020-10-15 20:18 UTC, KseniiaMakarova commented on src/main/java/com/dev/cinema/Main.java
>          authenticationService.register("email@mail.net", "1234");
let's wrap call to `login()` method in try-catch and add log.warn with the informative message in `catch` block

2020-10-16 07:10 UTC, Borisko130 commented on src/main/resources/log4j.properties
> +log4j.appender.STDOUT.layout=org.apache.log4j.PatternLayout
Not sure whether log4j.appender.CONSOLE should be replaced with log4j.appender.STDOUT so left both

2020-10-16 08:09 UTC, KseniiaMakarova approved these changes

2020-10-16 10:24 UTC, merged